- Object oriented programming(oops)

- Class:
    - Blueprint for creating an object
    - Collection of variables and methods

In [1]:
a = [1,2,3]
print(type(a))

<class 'list'>


In [2]:
print(dir(list))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [4]:
print(help(list.append))

Help on method_descriptor:

append(self, object, /)
    Append object to the end of the list.

None


In [7]:
class Person:
    age = 21
    def greet(self):
        print("Hello")
print(Person.greet)
print(Person.age)

<function Person.greet at 0x000001F677CFAA60>
21


### Object:

- Instance of class

In [17]:
class Person:
    age = 21
    def greet(self):
        print("Hello")
p = Person()
p.greet()

Hello


In [10]:
p.age

21

In [15]:
def add():
    c =2+3
    print(c)
add()

5


#### Constructors

In [19]:
class Apssdc:
    d = "python"
    def __init__(self):
        print("i am a constructor")
x = Apssdc()
x.d      
    

i am a constructor


'python'

In [26]:
class Apssdc:
    
    def __init__(self,a,b):
        print("i am a constructor")
        print(a,b)
x = Apssdc(10,20)
 

i am a constructor
10 20


In [27]:
class Apssdc:
    def __init__(self,name,number):
        self.name=name
        self.number=number
    def display(self):
        print(self.name)
        print(self.number)
    def display1(self):
        print(self.number)
x = Apssdc("alekhya",9876543210)  
x.display()

alekhya
9876543210


In [25]:
x.display1()

9876543210


### Inheritance


In [33]:
class A:#base class/parent class
    def details(self,name):
        self.name=name
        print(self.name)
class B(A):#derived class/chlid class
    def display(self):
        print("derived class")
z = B()
z.display()
z.details("alekhya")

derived class
alekhya


### Multiple Inheritance
- one class acquries the properties of one or more parent class

In [36]:
class A:
    def display(self):
        print("i am from a class")
class B:
    def display1(self):
        print("i am from b class")
class C(A,B):
    def display2(self):
        print("i am child class")
x = C()
x.display()
x.display1()
x.display2()

i am from a class
i am from b class
i am child class


In [37]:
#Multi level inheritance
class A:
    def display(self):
        print("i am from a class")
class B(A):
    def display1(self):
        print("i am from b class")
class C(B):
    def display2(self):
        print("i am child class")
x = C()
x.display()
x.display1()
x.display2()

i am from a class
i am from b class
i am child class


In [38]:
#modules
print(help("modules"))


Please wait a moment while I gather a list of all available modules...



C:\Users\Alekhya\Anaconda3\lib\site-packages\IPython\kernel\__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
C:\Users\Alekhya\Anaconda3\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
C:\Users\Alekhya\Anaconda3\lib\site-packages\distributed\config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
C:\Users\Alekhya\Anaconda3\lib\site-packages\nltk\twitter\__init__.py:22: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not b

DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: bzr
DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: git
DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: hg
DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: svn


C:\Users\Alekhya\Anaconda3\lib\site-packages\skimage\novice\__init__.py:103: UserWarning: The `skimage.novice` module was deprecated in version 0.14. It will be removed in 0.16.
  warnings.warn("The `skimage.novice` module was deprecated in version 0.14. "
C:\Users\Alekhya\Anaconda3\lib\site-packages\skimage\viewer\utils\core.py:10: UserWarning: Recommended matplotlib backend is `Agg` for full skimage.viewer functionality.
  warn("Recommended matplotlib backend is `Agg` for full "
C:\Users\Alekhya\Anaconda3\lib\site-packages\sphinx\websupport\__init__.py:25: RemovedInSphinx20Warning: sphinx.websupport module is now provided as sphinxcontrib-websupport. sphinx.websupport will be removed at Sphinx-2.0. Please use the package instead.
  RemovedInSphinx20Warning)
C:\Users\Alekhya\Anaconda3\lib\site-packages\qtawesome\iconic_font.py:276: UserWarning: You need to have a running QApplication to use QtAwesome!
  warnings.warn("You need to have a running "
C:\Users\Alekhya\Anaconda3\lib\pkgutil

Crypto              bz2                 menuinst            sortedcollections
Cython              cProfile            mimetypes           sortedcontainers
IPython             calendar            mistune             soupsieve
OpenSSL             certifi             mkl                 sphinx
PIL                 cffi                mkl_fft             sphinxcontrib
PyQt5               cgi                 mkl_random          spyder
__future__          cgitb               mmap                spyder_breakpoints
_abc                chardet             mmapfile            spyder_io_dcm
_ast                chunk               mmsystem            spyder_io_hdf5
_asyncio            click               modulefinder        spyder_kernels
_bisect             cloudpickle         more_itertools      spyder_profiler
_blake2             clyent              mpmath              spyder_pylint
_bootlocale         cmath               msgpack             sqlalchemy
_bz2                cmd                 msi

autoreload          inspect             quopri              win32ras
babel               io                  random              win32rcparser
backcall            ipaddress           rasutil             win32security
backports           ipykernel           re                  win32service
base64              ipykernel_launcher  readline            win32serviceutil
bcrypt              ipython_genutils    regcheck            win32timezone
bdb                 ipywidgets          regutil             win32trace
binascii            isapi               reprlib             win32traceutil
binhex              isort               requests            win32transaction
binstar_client      isympy              rlcompleter         win32ts
bisect              itertools           rmagic              win32ui
bitarray            itsdangerous        rope                win32uiole
bkcharts            jdcal               ruamel_yaml         win32verstamp
blaze               jedi                run            

In [39]:
pip list

Package                            Version
---------------------------------- ---------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.7
anaconda-project                   0.8.2
appdirs                            1.4.4
asn1crypto                         0.24.0
astroid                            2.2.5
astropy                            3.1.2
atomicwrites                       1.3.0
attrs                              19.1.0
Automat                            20.2.0
Babel                              2.6.0
backcall                           0.1.0
backports.os                       0.1.1
backports.shutil-get-terminal-size 1.0.0
bcrypt                             3.1.6
beautifulsoup4                     4.7.1
bitarray                           0.8.3
bkcharts                           0.2
blaze                              0.11.3
bleach                             3.1.0
bokeh                              1.0.4
boto   

testpath                           0.4.2
toolz                              0.9.0
tornado                            6.0.2
tqdm                               4.31.1
traitlets                          4.3.2
Twisted                            19.2.0
unicodecsv                         0.14.1
urllib3                            1.24.1
wcwidth                            0.1.7
webencodings                       0.5.1
Werkzeug                           0.14.1
wheel                              0.33.1
widgetsnbextension                 3.4.2
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.1
xlrd                               1.2.0
XlsxWriter                         1.1.5
xlwings                            0.15.4
xlwt                               1.3.0
zict                               0.1.4
zipp                               0.3.3
zope.interface                     4.6.0


You should consider upgrading via the 'C:\Users\Alekhya\Anaconda3\python.exe -m pip install --upgrade pip' command.


Note: you may need to restart the kernel to use updated packages.


In [41]:
import numpy

In [40]:
pip install numpy

You should consider upgrading via the 'C:\Users\Alekhya\Anaconda3\python.exe -m pip install --upgrade pip' command.


Note: you may need to restart the kernel to use updated packages.


In [42]:
import numpy as np
#numpy.org

In [43]:
# creating an array
# 1-d array


In [44]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [47]:
a = np.array([1,2,3,4,5])

In [48]:
a

array([1, 2, 3, 4, 5])

In [49]:
a.dtype

dtype('int32')

In [50]:
b = np.array(["a"])
b.dtype

dtype('<U1')

In [51]:
c = np.array(["a",9.7,34])

In [54]:
a = np.append(a,[6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [59]:
range(1,2.5)

TypeError: 'float' object cannot be interpreted as an integer

In [61]:
np.arange(1,21.5,2.5)

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5, 21. ])

In [65]:
a = np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [66]:
a.itemsize

8

In [67]:
len(a)

20

In [68]:
a.nbytes

160

In [69]:
np.full(10,"apssdc")

array(['apssdc', 'apssdc', 'apssdc', 'apssdc', 'apssdc', 'apssdc',
       'apssdc', 'apssdc', 'apssdc', 'apssdc'], dtype='<U6')

In [70]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [73]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [74]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [78]:
v = np.eye(5)
v

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
v.ndim

2

In [76]:
a = np.array([1,6,7])

In [77]:
a.ndim

1